### ISSUE TITLE
프로젝트 주제 확정 의견

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_Silbi#1]
어제 저희 주제에 대한  Presentation 발표가 있었습니다. 

### 주제: 실내 내부 점포 추천 시스템

어제 받은 피드백과 더불어 이 주제에 대해 확정할지, 아니면 수정할 부분이 있을 지에 대해 의견을 듣고 싶습니다.

**Comment by garamse** [comment]
같이온 나이대에 따라서 추천해줄 수 있는 점포들이 한계가 있기 때문에 가족끼리 왔다는 키워드에 유아들이 있을 경우와 청소년과 같은 나이대가 있을 경우도 고려해서 생각해보는게 좋을것 같습니다.

**Comment by rhdudtls** [comment]
주제는 확정하는 것이 좋을 것 같고, 크롤링을 통해서 같이 온 관계/현재 상태에 대한 키워드를 분배하는 방법이나 기술에 대해 좀 더 깊이 있게 생각해보아야 할 것 같습니다.

**Comment by kwongustj** [comment]
그렇다면 주제는 실내 내부 점포 추천 시스템으로 확정하면 될 것 같습니다.

그리고 앞으로 고민해야 할 부분

- 서버 관련
- 추천 시스템 기술
- 키워드 분배 기준 

을 앞으로 정리하면 될 것 같습니다
