### ISSUE TITLE
앱 기능 중 마이페이지의 내용에 대하여

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_Silbi#10]
로그인 / 회원가입 이후 마이페이지를 구현하기로 하였었는데, 마이페이지에서는 **_어떤 내용을 보여주면 좋을 지_** 의견을 제시해주시면 감사하겠습니다. 
일단은 대략적으로 사용자 개개인의 선택한 건물, 추천받은 날짜와 추천받은 점포들을 기록해 한눈에 볼 수 있도록 하는 것입니다.

**Comment by garamse** [comment]
마이페이지에서 추천받은 점포의 기록을 보여줄 때 자신이 한 별점 후기도 같이 보여주면 좋을 것 같습니다

**Comment by kwongustj** [comment]
자신이 한 별점은 추후 구현하기로 하였던걸로 기억합니다. 구현 완료되면 반영하도록하겠습니다 !!
