### ISSUE TITLE
프로젝트 역할 분담

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_Silbi#2]
**1. 프론트 (Android Studio-Java,Kotlin)
2. 백엔드(서버 + DB)
3. 크롤링 + 모델구현( Python )**

세 파트로 나누어 보았습니다.

저같은  경우는 세파트를  다 해봤는데
제 생각은 저만 프론트를 해본 거 같아서 제가 프론트를 빠르게 끝낸 후, 백엔드부분과 크롤링/모델구현 부분을 도와주는 것입니다.
각자 자신이 맡고 싶은 분야와 의견 주시기 바랍니다.

**Comment by rhdudtls** [comment]
DB를 다뤄본 적이 있어서 백엔드 쪽도 괜찮고 이번 기회에 크롤링을 제대로 해보는 것도 괜찮을 것 같습니다.
다른 분 의견도 들어보고 싶네요

**Comment by garamse** [comment]
크롤링을 조금 해본 적이 있어서  모델구현도 이번 기회에 한번 해보고싶습니다

**Comment by rhdudtls** [comment]
그럼 제가 백엔드를 맡아서 하겠습니다! 풀어나가기 어려울 때는 같이 돕기로해요~

**Comment by kwongustj** [comment]
그러면 그렇게 결정하도록 하겠습니다!

**Comment by bytecell** [comment]
Prof: Cafe 에서도 언급했듯이,
각자 개발에서 맡은 부분들을 진행하다가 생기는 것들을 각각 Issue 글로 파서 기록해도 되니 참고바랍니다.
