### ISSUE TITLE
Android 화면에 drawerLayout 추가

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_Silbi#25]
drawerLayout을 추가 하였습니다. 
목록에 무엇이 들어가면 좋을 지 의견 내주시면 감사할 것 같습니다!!

**Comment by rhdudtls** [comment]
건의사항을 전달할 수 있는 기능이 들어가면 좋을 것 같습니다.

**Comment by kwongustj** [comment]
확인하였습니다. 반영하겠습니다!!
