### ISSUE TITLE
키워드 관련 의견입니다!

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_Silbi#27]
키워드 부분이 같이 온 사람과의 관계 선택 -> 크롤링하여 형태소 분석하여 개수 센 키워드들 중 선택이었는데 교수님께서도 그렇고 그 사이가 붕 뜬다고 말씀하시기도 하여 조금 변경하는게 어떨 까 합니다.
중간에 큰 포괄적인 키워드를 더 선택하여 두번째 키워드 선택에 들어갈 키워드들이 어느정도 매치가 되게 하는 것입니다. 의견 부탁드립니다.
![image](https://user-images.githubusercontent.com/62468086/143850846-d99f9319-29c7-497d-84c8-4a395b5c13ad.png)

**Comment by rhdudtls** [comment]
한 번 큰 주제를 고르고 연관된 주제 안에서 자세한 키워드를 고를 수 있게 되는 것이 기존 방식보다 더 좋을 것 같습니다.

**Comment by kwongustj** [comment]
네 알겠습니다. 그렇게 생각하고 구현해보겠습니다
