### ISSUE TITLE
기술 구현 관련 개발 도구 결정 사항 

### ISSUE THREAD

**Issue by rhdudtls** [kwongustj/project_Silbi#3]
제가 자바를 다뤄본 적이 없어서 소스도 많고 조금이라도 익숙한 파이썬을 사용하고 싶은데 어플로 개발 시  flask, django 중 어느 것을 사용할 것인지에 대한 고민이 필요할 것 같습니다. 의견 부탁드려요.

**Comment by garamse** [comment]
설정하고 셋팅할게 많은 flask 보다 django가 낫다고 생각합니다!

**Comment by kwongustj** [comment]
학습용으로는 Flask가 좋다고 들은 적이 있습니다! 저희는 공부하는 입장이니 Flask가 어떤가요 ?

**Comment by rhdudtls** [comment]
입문용으로는 Flask가 좋다는 이야기가 많아서 Flask로 하는 것이 좋을 것 같네요!
